[workspace]
members = ["contracts/*", "packages/*", "scripts"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "GPL-3.0-or-later"
license-file = "LICENSE"
repository = "https://github.com/Arena-DAO/arena-smart-contracts"
version = "3.0.0"

[workspace.metadata]
documentation = "https://docs.arenadao.org"
issues = "https://github.com/arena-dao/arena-smart-contracts/issues"

[profile.release]
strip = true
codegen-units = 1
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
cosmwasm-std = { version = "2.2.2", features = ["cosmwasm_2_2"] }
cosmwasm-storage = "1.5.2"
cosmwasm-schema = "2.2.2"
cw-utils = "2.0.0"
thiserror = "2.0.12"
cw-storage-plus = "2.0.0"
cw-multi-test = { version = "2.3.3", features = ["cosmwasm_2_2"] }
cw2 = "2.0.0"
cw20 = "2.0.0"
cw20-base = "2.0.0"
anyhow = "1.0.98"
cw4-group = "2.0.0"
cw4 = "2.0.0"
serde = { version = "1", default-features = false, features = ["derive"] }
cw-paginate = "2.0.0"
cw-ownable = "2.1.0"
cw-address-like = "2.0.0"
itertools = "0.14.0"
cw-orch = "0.28.0"
semver = "1.0.26"
rust_decimal = "1.37.1"
rust_decimal_macros = "1.37.1"
serde_json = "1.0.140"
sha2 = { version = "0.10.9", default-features = false }

# cw-nfts
cw721 = { git = "https://github.com/public-awesome/cw-nfts" }
cw721-base = { git = "https://github.com/public-awesome/cw-nfts" }

#arena_dao dependencies
cw-competition-base = { path = "./packages/cw-competition-base" }
cw-balance = { path = "./packages/cw-balance" }
arena-interface = { path = "./packages/arena-interface" }
orch-interface = { path = "./packages/orch-interface" }
glicko_2 = { path = "./packages/glicko_2" }

arena-core = { path = "./contracts/arena-core" }
arena-discord-identity = { path = "./contracts/arena-discord-identity" }
arena-escrow = { path = "./contracts/arena-escrow" }
arena-group = { path = "./contracts/arena-group" }
arena-wager-module = { path = "./contracts/arena-wager-module" }
arena-league-module = { path = "./contracts/arena-league-module" }
arena-tournament-module = { path = "./contracts/arena-tournament-module" }
arena-competition-enrollment = { path = "./contracts/arena-competition-enrollment" }
arena-payment-registry = { path = "./contracts/arena-payment-registry" }
arena-team-enrollments = { path = "./contracts/arena-team-enrollments" }

#dao dependencies
dao-interface = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-cw-orch = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-proposal-single = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-pre-propose-single = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-voting = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-voting-cw4 = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-proposal-sudo = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-pre-propose-base = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
dao-dao-core = { git = "https://github.com/Arena-DAO/dao-contracts", branch = "arena-dao" }
